
@baseUrl = http://localhost:4004/odata/v4

# POST http://localhost:4004/odata/v4/catalog/insertTBProducts
# Content-Type: application/json


# POST http://localhost:4004/odata/v4/catalog/insertTBSuppliers
#  Content-Type: application/json

# POST http://localhost:4004/odata/v4/catalog/insertTBCategories
# Content-Type: application/json

GET http://localhost:4004/odata/v4/catalog/GetCatalog()



# {
#   "items": [
#     {
#       "CategoryID": 1,
#       "CategoryName": "Beverages",
#       "Description": "Soft drinks, coffees, teas, beers, and ales"
#     }
#    ]
# }



### 1
#POST {{baseUrl}}/catalog/LogBooks HTTP/1.1
#Content-Type: application/json

#{
#  "borrowerName": "Hello",
#  "bookTitle": "Clean Code",
#  "authorName": "Robert C. Martin",
#  "readDate": "{{$datetime 'YYYY-MM-DD'}}"
#}

### 2
#POST {{baseUrl}}/catalog/LogBooks HTTP/1.1
#Content-Type: application/json

#{
#  "borrowerName": "B-1002",
#  "bookTitle": "The Pragmatic Programmer",
#  "authorName": "Andrew Hunt",
#  "readDate": "{{$datetime 'YYYY-MM-DD'}}"
#}

### 3
#POST {{baseUrl}}/catalog/LogBooks HTTP/1.1
#Content-Type: application/json

#{
#  "borrowerName": "B-1003",
#  "bookTitle": "Design Patterns",
#  "authorName": "Gamma et al.",
#  "readDate": "{{$datetime 'YYYY-MM-DD'}}"
#}

### 4
#POST {{baseUrl}}/catalog/LogBooks HTTP/1.1
#Content-Type: application/json

#{
#  "borrowerName": "Josh",
#  "bookTitle": "Refactoring",
#  "authorName": "Martin Fowler",
#  "readDate": "{{$datetime 'YYYY-MM-DD'}}"
#}

### 5
#POST {{baseUrl}}/catalog/LogBooks HTTP/1.1
#Content-Type: application/json

#{
# "borrowerName": "Karina",
#  "bookTitle": "Programming",
#  "authorName": "Rochelle Solinap",
#  "readDate": "{{$datetime 'YYYY-MM-DD'}}"
#}

# Fetch all logs# Fetch all logs for a borrower (descending by borrowerName)


# POST http://localhost:4004/odata/v4/catalog/FetchBooks
# Content-Type: application/json

# {
#   "borrowerName": "Karina"
# }
